image: golang:latest

variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - build
  - test

build_certify:
  artifacts:
    paths:
      - build/
  script:
    - make
  stage: build

unit_tests:
  script:
    - make gitlab-cover
  stage: test
